name: Bump Version

on:
  push:
    branches:
      - master
    paths:
      - repos/**

jobs:
  bump-version:
    runs-on: ubuntu-18.04
    steps:
      - uses: purcell/setup-emacs@b56a75706e31e22d474357c77fb25ce73be2973a
        with:
          version: '27.2'
      - uses: actions/checkout@v2

      - name: Print commit data
        uses: actions/github-script@v5
        with:
          script: |
            let commit = github.rest.git.getCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: context.sha
            });
            console.log(commit);
            let m = commit.message.match(/!bump-version(.*)$/m)
            let version = typeof m[1] == 'string' ? m[1].trim() : ''
            console.log(version);
        continue-on-error: true

      - name: Bump version
        run: script/dev bump-version

      # We don't want this to trigger workflows, so we don't use a personal access token.
      - name: Create the release commit
        # TODO: Sign the tag?
        run: |
          git add --update
          git config --global user.name 'Tuấn-Anh Nguyễn'
          git config --global user.email 'ubolonton@users.noreply.github.com'
          RELEASE_VERSION=$(script/dev current-version)
          git commit -m "Release $RELEASE_VERSION"
          echo RELEASE_VERSION=$RELEASE_VERSION >> $GITHUB_ENV
          echo RELEASE_SHA=$(git rev-parse HEAD) >> $GITHUB_ENV
          git push

      - name: Create the release tag
        uses: actions/github-script@v4
        with:
          # Use personal access token to trigger the release workflow.
          github-token: ${{ secrets.PAT }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ env.RELEASE_VERSION }}",
              sha: "${{ env.RELEASE_SHA }}"
            })
